version: "3.7"
services:
  redis:
    image: "redis:alpine"
    network_mode: "host"
  backend:
    image: sanbonai06/hmut-server:latest
    env_file:
      - ../.env
    container_name: backend
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
    expose:
      - "8080"

  nginx:
    depends_on:
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"
