spring:
  profiles:
    include:
      - domain
      - core
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger:
  user: ${SWAGGER_USER:user}
  password: ${SWAGGER_PASSWORD:password}