auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY:testkeytestkeytestkeytestkeytestkeytestkeytestkeytestkeytestkey}
    access-exp: ${JWT_ACCESS_EXP:3600}
    refresh-exp: ${JWT_REFRESH_EXP:3600}
    issuer: ${JWT_ISSUER:test}

oauth2:
  kakao:
    infoUrl: https://kapi.kakao.com
    baseUrl: https://kauth.kakao.com
    clientId: 5d38e6dc1f62b10c9r3dc2e34fe6d24e62
    redirectUri: http://localhost/api/v1/login/kakao/oauth2
    secretKey: I1nEw554k2oFM1n32P126Yro7NrRVU2G